name: Davesmicrogreens
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1004296
title: "Dave's Microgreens"
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050605'
    - '#C4BEBE'
    - '#1FC4BE'
    - '#91BD4B'
    - '#FAFC65'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
